"""OpsMind AI — Parameterized SQL queries for the Streamlit Command Center.

All queries use parameterized binding where applicable. Governance
mutations go through stored procedures via CALL, never direct DML.
"""

# -- Operations Overview ---------------------------------------------------

FLEET_RISK_SUMMARY = """
SELECT
    RISK_BAND,
    COUNT(*) AS MACHINE_COUNT
FROM OPSMIND.AI.FAILURE_RISK_SCORES
GROUP BY RISK_BAND
ORDER BY CASE RISK_BAND
    WHEN 'CRITICAL' THEN 1
    WHEN 'HIGH' THEN 2
    WHEN 'MEDIUM' THEN 3
    WHEN 'LOW' THEN 4
    WHEN 'INCOMPLETE' THEN 5
END
"""

OEE_FLEET_LATEST = """
SELECT
    M.MACHINE_ID,
    M.MACHINE_NAME,
    M.MACHINE_TYPE,
    PL.LINE_NAME,
    O.METRIC_DATE,
    O.OEE_PCT,
    O.AVAILABILITY_PCT,
    O.PERFORMANCE_PCT,
    O.QUALITY_PCT
FROM OPSMIND.CORE.OEE_METRICS O
JOIN OPSMIND.CORE.MACHINES M ON O.MACHINE_ID = M.MACHINE_ID
JOIN OPSMIND.CORE.PRODUCTION_LINES PL ON M.LINE_ID = PL.LINE_ID
WHERE O.METRIC_DATE = (SELECT MAX(METRIC_DATE) FROM OPSMIND.CORE.OEE_METRICS)
ORDER BY O.OEE_PCT ASC
"""

ANOMALY_RECENT = """
SELECT
    A.ANOMALY_ID,
    A.MACHINE_ID,
    M.MACHINE_NAME,
    A.SIGNAL_TYPE,
    A.SEVERITY,
    A.DEVIATION_PCT,
    A.CONFIDENCE_SCORE,
    A.DETECTED_AT,
    A.DESCRIPTION
FROM OPSMIND.CORE.ANOMALY_SIGNALS A
JOIN OPSMIND.CORE.MACHINES M ON A.MACHINE_ID = M.MACHINE_ID
ORDER BY A.DETECTED_AT DESC
LIMIT 20
"""

PLANT_SUMMARY = """
SELECT
    P.PLANT_NAME,
    P.REGION,
    COUNT(DISTINCT PL.LINE_ID) AS LINE_COUNT,
    COUNT(DISTINCT M.MACHINE_ID) AS MACHINE_COUNT
FROM OPSMIND.CORE.PLANTS P
JOIN OPSMIND.CORE.PRODUCTION_LINES PL ON P.PLANT_ID = PL.PLANT_ID
JOIN OPSMIND.CORE.MACHINES M ON PL.LINE_ID = M.LINE_ID
GROUP BY P.PLANT_NAME, P.REGION
"""

# -- Asset Intelligence ----------------------------------------------------

RISK_SCORES_ALL = """
SELECT
    MACHINE_ID, MACHINE_NAME, MACHINE_TYPE, CRITICALITY_RATING,
    RISK_SCORE, RISK_BAND, DATA_QUALITY, DATA_COMPLETENESS_PCT,
    VIBRATION_LEVEL_SCORE, VIBRATION_TREND_SCORE,
    THERMAL_DEVIATION_SCORE, OEE_DEGRADATION_SCORE,
    MAINTENANCE_OVERDUE_SCORE,
    LATEST_VIBRATION, LATEST_BEARING_TEMP, LATEST_OEE,
    BASELINE_OEE, IS_OVERDUE, DAYS_OVERDUE,
    AS_OF_DATE, LOOKBACK_WINDOW_DAYS, METHOD_VERSION
FROM OPSMIND.AI.FAILURE_RISK_SCORES
ORDER BY RISK_SCORE DESC NULLS LAST
"""

OEE_TREND_FOR_MACHINE = """
SELECT
    O.METRIC_DATE,
    O.OEE_PCT,
    O.AVAILABILITY_PCT,
    O.PERFORMANCE_PCT,
    O.QUALITY_PCT
FROM OPSMIND.CORE.OEE_METRICS O
WHERE O.MACHINE_ID = ?
ORDER BY O.METRIC_DATE
"""

SENSOR_TREND_FOR_MACHINE = """
SELECT
    S.READING_TS,
    S.SENSOR_TYPE,
    S.VALUE,
    S.UNIT
FROM OPSMIND.CORE.SENSOR_READINGS S
WHERE S.MACHINE_ID = ?
  AND S.SENSOR_TYPE IN ('vibration', 'bearing_temp')
ORDER BY S.READING_TS
"""

MAINTENANCE_FOR_MACHINE = """
SELECT
    MH.TASK_ID,
    MH.TASK_TYPE,
    MH.STATUS,
    MH.SCHEDULED_DATE,
    MH.COMPLETED_DATE,
    MH.DESCRIPTION
FROM OPSMIND.CORE.MAINTENANCE_HISTORY MH
WHERE MH.MACHINE_ID = ?
ORDER BY MH.SCHEDULED_DATE DESC
"""

FAILURE_HISTORY_FOR_MACHINE = """
SELECT
    F.FAILURE_ID,
    F.FAILURE_MODE,
    F.SEVERITY,
    F.ROOT_CAUSE,
    F.FAILURE_START,
    F.FAILURE_END,
    F.DOWNTIME_MINUTES,
    F.REPAIR_COST_USD
FROM OPSMIND.CORE.FAILURE_HISTORY F
WHERE F.MACHINE_ID = ?
ORDER BY F.FAILURE_START DESC
"""

IMPACT_FOR_MACHINE = """
SELECT
    ASSUMPTION_ID,
    FAILURE_COMPONENT,
    ASSUMPTION_SOURCE,
    ASSUMPTION_BASIS,
    ESTIMATED_TOTAL_PLANNED_INTERVENTION_USD,
    ESTIMATED_TOTAL_UNPLANNED_FAILURE_USD,
    ESTIMATED_POTENTIAL_AVOIDED_IMPACT_USD,
    ESTIMATED_AVOIDED_DOWNTIME_HRS,
    PLANNED_DOWNTIME_HRS,
    UNPLANNED_DOWNTIME_HRS
FROM OPSMIND.AI.IMPACT_SCENARIOS
WHERE MACHINE_ID = ?
"""

# -- Decision Center -------------------------------------------------------

PENDING_RECOMMENDATIONS = """
SELECT
    RECOMMENDATION_ID,
    MACHINE_ID,
    ACTION_TYPE,
    PRIORITY,
    DESCRIPTION,
    RATIONALE,
    EVIDENCE_SUMMARY,
    ESTIMATED_COST_USD,
    ESTIMATED_DOWNTIME_HRS,
    RISK_IF_DEFERRED,
    GENERATED_AT
FROM OPSMIND.AI.RECOMMENDATIONS
WHERE STATUS = 'pending'
ORDER BY
    CASE PRIORITY
        WHEN 'critical' THEN 1
        WHEN 'high' THEN 2
        WHEN 'medium' THEN 3
        WHEN 'low' THEN 4
    END,
    GENERATED_AT DESC
"""

ALL_RECOMMENDATIONS = """
SELECT
    RECOMMENDATION_ID,
    MACHINE_ID,
    ACTION_TYPE,
    PRIORITY,
    STATUS,
    DESCRIPTION,
    GENERATED_AT
FROM OPSMIND.AI.RECOMMENDATIONS
ORDER BY GENERATED_AT DESC
"""

APPROVED_READY_TO_EXECUTE = """
SELECT
    AD.APPROVAL_ID,
    AD.RECOMMENDATION_ID,
    AD.DECIDED_BY,
    AD.DECISION_AT AS DECIDED_AT,
    AD.COMMENTS,
    R.MACHINE_ID,
    R.ACTION_TYPE,
    R.DESCRIPTION AS REC_DESCRIPTION
FROM OPSMIND.GOVERNANCE.APPROVAL_DECISIONS AD
JOIN OPSMIND.AI.RECOMMENDATIONS R
    ON AD.RECOMMENDATION_ID = R.RECOMMENDATION_ID
WHERE AD.DECISION = 'approved'
  AND R.STATUS = 'approved'
  AND NOT EXISTS (
      SELECT 1 FROM OPSMIND.GOVERNANCE.EXECUTED_ACTIONS EA
      WHERE EA.APPROVAL_ID = AD.APPROVAL_ID
  )
ORDER BY AD.DECIDED_AT DESC
"""

# -- Audit & Governance ----------------------------------------------------

AUDIT_LOG_RECENT = """
SELECT
    AUDIT_ID,
    EVENT_TYPE,
    ENTITY_TYPE,
    ENTITY_ID,
    ACTOR,
    EVENT_TS,
    DETAILS
FROM OPSMIND.GOVERNANCE.AUDIT_LOG
ORDER BY EVENT_TS DESC
LIMIT 50
"""

APPROVAL_DECISIONS_RECENT = """
SELECT
    APPROVAL_ID,
    RECOMMENDATION_ID,
    DECISION,
    DECIDED_BY,
    DECISION_AT AS DECIDED_AT,
    COMMENTS
FROM OPSMIND.GOVERNANCE.APPROVAL_DECISIONS
ORDER BY DECISION_AT DESC
LIMIT 20
"""

EXECUTED_ACTIONS_RECENT = """
SELECT
    ACTION_ID,
    APPROVAL_ID,
    ACTION_TYPE,
    DESCRIPTION,
    EXECUTED_BY,
    EXECUTED_AT,
    RESULT
FROM OPSMIND.GOVERNANCE.EXECUTED_ACTIONS
ORDER BY EXECUTED_AT DESC
LIMIT 20
"""
