-- ============================================================
-- OpsMind AI — 03_tables.sql
-- All table DDL across schemas
-- ============================================================

USE DATABASE OPSMIND;

-- ============================================================
-- CORE schema — Investigation inputs
-- ============================================================
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS PLANTS (
    PLANT_ID        VARCHAR(20)   NOT NULL,
    PLANT_NAME      VARCHAR(100)  NOT NULL,
    REGION          VARCHAR(50)   NOT NULL,
    TIMEZONE        VARCHAR(50)   NOT NULL,
    PLANT_TYPE      VARCHAR(50)   NOT NULL,
    CONSTRAINT PK_PLANTS PRIMARY KEY (PLANT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCTION_LINES (
    LINE_ID                  VARCHAR(20)   NOT NULL,
    PLANT_ID                 VARCHAR(20)   NOT NULL,
    LINE_NAME                VARCHAR(100)  NOT NULL,
    PRODUCT_TYPE             VARCHAR(100)  NOT NULL,
    DESIGN_CAPACITY_UNITS_HR INTEGER       NOT NULL,
    CONSTRAINT PK_PRODUCTION_LINES PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_LINES_PLANT FOREIGN KEY (PLANT_ID) REFERENCES PLANTS(PLANT_ID)
);

CREATE TABLE IF NOT EXISTS MACHINES (
    MACHINE_ID         VARCHAR(20)   NOT NULL,
    LINE_ID            VARCHAR(20)   NOT NULL,
    MACHINE_NAME       VARCHAR(100)  NOT NULL,
    MACHINE_TYPE       VARCHAR(50)   NOT NULL,
    MANUFACTURER       VARCHAR(100)  NOT NULL,
    MODEL              VARCHAR(50)   NOT NULL,
    INSTALL_DATE       DATE          NOT NULL,
    LAST_OVERHAUL_DATE DATE,
    STATUS             VARCHAR(20)   NOT NULL,
    CRITICALITY_RATING INTEGER       NOT NULL,
    CONSTRAINT PK_MACHINES PRIMARY KEY (MACHINE_ID),
    CONSTRAINT FK_MACHINES_LINE FOREIGN KEY (LINE_ID) REFERENCES PRODUCTION_LINES(LINE_ID)
);

CREATE TABLE IF NOT EXISTS SENSOR_READINGS (
    READING_ID  VARCHAR(20)      NOT NULL,
    MACHINE_ID  VARCHAR(20)      NOT NULL,
    READING_TS  TIMESTAMP_NTZ    NOT NULL,
    SENSOR_TYPE VARCHAR(30)      NOT NULL,
    VALUE       FLOAT            NOT NULL,
    UNIT        VARCHAR(10)      NOT NULL,
    CONSTRAINT PK_SENSOR_READINGS PRIMARY KEY (READING_ID),
    CONSTRAINT FK_SENSORS_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES MACHINES(MACHINE_ID)
);

CREATE TABLE IF NOT EXISTS OEE_METRICS (
    OEE_ID               VARCHAR(20)   NOT NULL,
    MACHINE_ID           VARCHAR(20)   NOT NULL,
    METRIC_DATE          DATE          NOT NULL,
    SHIFT                VARCHAR(10)   NOT NULL,
    AVAILABILITY_PCT     FLOAT         NOT NULL,
    PERFORMANCE_PCT      FLOAT         NOT NULL,
    QUALITY_PCT          FLOAT         NOT NULL,
    OEE_PCT              FLOAT         NOT NULL,
    PLANNED_PRODUCTION_HRS FLOAT       NOT NULL,
    ACTUAL_PRODUCTION_HRS  FLOAT       NOT NULL,
    UNITS_PRODUCED       INTEGER       NOT NULL,
    UNITS_DEFECTIVE      INTEGER       NOT NULL,
    DOWNTIME_MINUTES     INTEGER       NOT NULL,
    CONSTRAINT PK_OEE_METRICS PRIMARY KEY (OEE_ID),
    CONSTRAINT FK_OEE_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES MACHINES(MACHINE_ID)
);

CREATE TABLE IF NOT EXISTS MAINTENANCE_HISTORY (
    MAINTENANCE_ID   VARCHAR(20)    NOT NULL,
    MACHINE_ID       VARCHAR(20)    NOT NULL,
    SCHEDULED_DATE   TIMESTAMP_NTZ  NOT NULL,
    COMPLETED_DATE   TIMESTAMP_NTZ,
    MAINTENANCE_TYPE VARCHAR(20)    NOT NULL,
    DESCRIPTION      VARCHAR(500)   NOT NULL,
    COMPONENT        VARCHAR(50)    NOT NULL,
    TECHNICIAN       VARCHAR(100),
    STATUS           VARCHAR(20)    NOT NULL,
    COST_USD         FLOAT,
    CONSTRAINT PK_MAINTENANCE PRIMARY KEY (MAINTENANCE_ID),
    CONSTRAINT FK_MAINT_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES MACHINES(MACHINE_ID)
);

CREATE TABLE IF NOT EXISTS FAILURE_HISTORY (
    FAILURE_ID       VARCHAR(20)    NOT NULL,
    MACHINE_ID       VARCHAR(20)    NOT NULL,
    FAILURE_START    TIMESTAMP_NTZ  NOT NULL,
    FAILURE_END      TIMESTAMP_NTZ,
    FAILURE_MODE     VARCHAR(50)    NOT NULL,
    ROOT_CAUSE       VARCHAR(200)   NOT NULL,
    SEVERITY         VARCHAR(20)    NOT NULL,
    DOWNTIME_MINUTES INTEGER        NOT NULL,
    REPAIR_COST_USD  FLOAT          NOT NULL,
    CORRECTIVE_ACTION VARCHAR(500)  NOT NULL,
    CONSTRAINT PK_FAILURES PRIMARY KEY (FAILURE_ID),
    CONSTRAINT FK_FAIL_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES MACHINES(MACHINE_ID)
);

CREATE TABLE IF NOT EXISTS WORK_ORDERS (
    WO_ID              VARCHAR(20)    NOT NULL,
    MACHINE_ID         VARCHAR(20)    NOT NULL,
    CREATED_DATE       TIMESTAMP_NTZ  NOT NULL,
    DUE_DATE           TIMESTAMP_NTZ,
    COMPLETED_DATE     TIMESTAMP_NTZ,
    WO_TYPE            VARCHAR(20)    NOT NULL,
    PRIORITY           VARCHAR(20)    NOT NULL,
    STATUS             VARCHAR(20)    NOT NULL,
    DESCRIPTION        VARCHAR(500)   NOT NULL,
    ASSIGNED_TO        VARCHAR(100),
    ESTIMATED_COST_USD FLOAT,
    ACTUAL_COST_USD    FLOAT,
    CONSTRAINT PK_WORK_ORDERS PRIMARY KEY (WO_ID),
    CONSTRAINT FK_WO_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES MACHINES(MACHINE_ID)
);

-- ============================================================
-- KNOWLEDGE schema — Unstructured documents
-- ============================================================
USE SCHEMA KNOWLEDGE;

CREATE TABLE IF NOT EXISTS OPERATIONAL_DOCUMENTS (
    DOC_ID                    VARCHAR(20)    NOT NULL,
    PLANT_ID                  VARCHAR(20),
    DOC_TYPE                  VARCHAR(30)    NOT NULL,
    TITLE                     VARCHAR(200)   NOT NULL,
    CONTENT                   VARCHAR(16777216) NOT NULL,
    APPLICABLE_MACHINE_TYPES  VARCHAR(200),
    APPLICABLE_COMPONENTS     VARCHAR(200),
    LAST_UPDATED              TIMESTAMP_NTZ  NOT NULL,
    VERSION                   VARCHAR(10)    NOT NULL,
    CONSTRAINT PK_DOCS PRIMARY KEY (DOC_ID)
);

-- ============================================================
-- AI schema — System-generated analytical outputs
-- ============================================================
USE SCHEMA AI;

CREATE TABLE IF NOT EXISTS ANOMALY_SIGNALS (
    ANOMALY_ID       VARCHAR(20)    NOT NULL,
    MACHINE_ID       VARCHAR(20)    NOT NULL,
    DETECTED_AT      TIMESTAMP_NTZ  NOT NULL,
    SIGNAL_TYPE      VARCHAR(30)    NOT NULL,
    SEVERITY         VARCHAR(20)    NOT NULL,
    DESCRIPTION      VARCHAR(500)   NOT NULL,
    CONFIDENCE_SCORE FLOAT          NOT NULL,
    SOURCE_METRIC    VARCHAR(30)    NOT NULL,
    BASELINE_VALUE   FLOAT          NOT NULL,
    OBSERVED_VALUE   FLOAT          NOT NULL,
    DEVIATION_PCT    FLOAT          NOT NULL,
    CONSTRAINT PK_ANOMALIES PRIMARY KEY (ANOMALY_ID)
);

CREATE TABLE IF NOT EXISTS RECOMMENDATIONS (
    RECOMMENDATION_ID  VARCHAR(20)    NOT NULL,
    ANOMALY_ID         VARCHAR(20)    NOT NULL,
    MACHINE_ID         VARCHAR(20)    NOT NULL,
    GENERATED_AT       TIMESTAMP_NTZ  NOT NULL,
    ACTION_TYPE        VARCHAR(30)    NOT NULL,
    PRIORITY           VARCHAR(20)    NOT NULL,
    DESCRIPTION        VARCHAR(500)   NOT NULL,
    RATIONALE          VARCHAR(2000)  NOT NULL,
    EVIDENCE_SUMMARY   VARCHAR(2000)  NOT NULL,
    ESTIMATED_COST_USD FLOAT          NOT NULL,
    ESTIMATED_DOWNTIME_HRS FLOAT      NOT NULL,
    RISK_IF_DEFERRED   VARCHAR(500)   NOT NULL,
    STATUS             VARCHAR(20)    NOT NULL,
    CONSTRAINT PK_RECOMMENDATIONS PRIMARY KEY (RECOMMENDATION_ID),
    CONSTRAINT FK_REC_ANOMALY FOREIGN KEY (ANOMALY_ID) REFERENCES ANOMALY_SIGNALS(ANOMALY_ID)
);

-- ============================================================
-- GOVERNANCE schema — Human decisions and audit
-- ============================================================
USE SCHEMA GOVERNANCE;

CREATE TABLE IF NOT EXISTS APPROVAL_DECISIONS (
    APPROVAL_ID        VARCHAR(20)    NOT NULL,
    RECOMMENDATION_ID  VARCHAR(20)    NOT NULL,
    DECISION_AT        TIMESTAMP_NTZ  NOT NULL,
    DECIDED_BY         VARCHAR(100)   NOT NULL,
    DECISION           VARCHAR(20)    NOT NULL,
    COMMENTS           VARCHAR(1000),
    CONSTRAINT PK_APPROVALS PRIMARY KEY (APPROVAL_ID)
);

CREATE TABLE IF NOT EXISTS EXECUTED_ACTIONS (
    ACTION_ID    VARCHAR(20)    NOT NULL,
    APPROVAL_ID  VARCHAR(20)    NOT NULL,
    WO_ID        VARCHAR(20),
    EXECUTED_AT  TIMESTAMP_NTZ  NOT NULL,
    ACTION_TYPE  VARCHAR(30)    NOT NULL,
    DESCRIPTION  VARCHAR(500)   NOT NULL,
    EXECUTED_BY  VARCHAR(100)   NOT NULL,
    RESULT       VARCHAR(500)   NOT NULL,
    CONSTRAINT PK_ACTIONS PRIMARY KEY (ACTION_ID),
    CONSTRAINT FK_ACT_APPROVAL FOREIGN KEY (APPROVAL_ID) REFERENCES APPROVAL_DECISIONS(APPROVAL_ID)
);

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    AUDIT_ID    VARCHAR(20)    NOT NULL,
    ENTITY_TYPE VARCHAR(30)    NOT NULL,
    ENTITY_ID   VARCHAR(20)    NOT NULL,
    EVENT_TS    TIMESTAMP_NTZ  NOT NULL,
    EVENT_TYPE  VARCHAR(20)    NOT NULL,
    ACTOR       VARCHAR(100)   NOT NULL,
    DETAILS     VARCHAR(1000)  NOT NULL,
    CONSTRAINT PK_AUDIT PRIMARY KEY (AUDIT_ID)
);
