-- ============================================================
-- OpsMind AI — 05_load_seed_data.sql
-- Load seed CSV data from internal stage into tables
-- ============================================================
-- Prerequisites:
--   1. Tables created (03_tables.sql)
--   2. Stage/formats created (04_stages_file_formats.sql)
--   3. CSV files uploaded to @OPSMIND.RAW.SEED_DATA_STAGE/
--      via: scripts/upload_seed_data.py or manual PUT
-- ============================================================

USE DATABASE OPSMIND;
USE WAREHOUSE OPSMIND_WH;

-- Truncate before load for idempotency
TRUNCATE TABLE IF EXISTS CORE.PLANTS;
TRUNCATE TABLE IF EXISTS CORE.PRODUCTION_LINES;
TRUNCATE TABLE IF EXISTS CORE.MACHINES;
TRUNCATE TABLE IF EXISTS CORE.SENSOR_READINGS;
TRUNCATE TABLE IF EXISTS CORE.OEE_METRICS;
TRUNCATE TABLE IF EXISTS CORE.MAINTENANCE_HISTORY;
TRUNCATE TABLE IF EXISTS CORE.FAILURE_HISTORY;
TRUNCATE TABLE IF EXISTS CORE.WORK_ORDERS;
TRUNCATE TABLE IF EXISTS KNOWLEDGE.OPERATIONAL_DOCUMENTS;
TRUNCATE TABLE IF EXISTS AI.ANOMALY_SIGNALS;
TRUNCATE TABLE IF EXISTS AI.RECOMMENDATIONS;
TRUNCATE TABLE IF EXISTS GOVERNANCE.APPROVAL_DECISIONS;
TRUNCATE TABLE IF EXISTS GOVERNANCE.EXECUTED_ACTIONS;
TRUNCATE TABLE IF EXISTS GOVERNANCE.AUDIT_LOG;

-- Load CORE tables (order respects FK dependencies)
COPY INTO CORE.PLANTS
    FROM @RAW.SEED_DATA_STAGE/plants.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CORE.PRODUCTION_LINES
    FROM @RAW.SEED_DATA_STAGE/production_lines.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CORE.MACHINES
    FROM @RAW.SEED_DATA_STAGE/machines.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CORE.SENSOR_READINGS
    FROM @RAW.SEED_DATA_STAGE/sensor_readings.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CORE.OEE_METRICS
    FROM @RAW.SEED_DATA_STAGE/oee_metrics.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CORE.MAINTENANCE_HISTORY
    FROM @RAW.SEED_DATA_STAGE/maintenance_history.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CORE.FAILURE_HISTORY
    FROM @RAW.SEED_DATA_STAGE/failure_history.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CORE.WORK_ORDERS
    FROM @RAW.SEED_DATA_STAGE/work_orders.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

-- Load KNOWLEDGE
COPY INTO KNOWLEDGE.OPERATIONAL_DOCUMENTS
    FROM @RAW.SEED_DATA_STAGE/operational_documents.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

-- Load AI outputs
COPY INTO AI.ANOMALY_SIGNALS
    FROM @RAW.SEED_DATA_STAGE/anomaly_signals.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO AI.RECOMMENDATIONS
    FROM @RAW.SEED_DATA_STAGE/recommendations.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

-- Load GOVERNANCE
COPY INTO GOVERNANCE.APPROVAL_DECISIONS
    FROM @RAW.SEED_DATA_STAGE/approval_decisions.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO GOVERNANCE.EXECUTED_ACTIONS
    FROM @RAW.SEED_DATA_STAGE/executed_actions.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO GOVERNANCE.AUDIT_LOG
    FROM @RAW.SEED_DATA_STAGE/audit_log.csv
    FILE_FORMAT = RAW.CSV_FORMAT
    ON_ERROR = 'ABORT_STATEMENT';
