-- ============================================================
-- OpsMind AI — 06_validate.sql
-- Post-deployment validation queries
-- ============================================================

USE DATABASE OPSMIND;
USE WAREHOUSE OPSMIND_WH;

-- Row counts
SELECT 'CORE.PLANTS' AS table_name, COUNT(*) AS row_count FROM CORE.PLANTS
UNION ALL SELECT 'CORE.PRODUCTION_LINES', COUNT(*) FROM CORE.PRODUCTION_LINES
UNION ALL SELECT 'CORE.MACHINES', COUNT(*) FROM CORE.MACHINES
UNION ALL SELECT 'CORE.SENSOR_READINGS', COUNT(*) FROM CORE.SENSOR_READINGS
UNION ALL SELECT 'CORE.OEE_METRICS', COUNT(*) FROM CORE.OEE_METRICS
UNION ALL SELECT 'CORE.MAINTENANCE_HISTORY', COUNT(*) FROM CORE.MAINTENANCE_HISTORY
UNION ALL SELECT 'CORE.FAILURE_HISTORY', COUNT(*) FROM CORE.FAILURE_HISTORY
UNION ALL SELECT 'CORE.WORK_ORDERS', COUNT(*) FROM CORE.WORK_ORDERS
UNION ALL SELECT 'KNOWLEDGE.OPERATIONAL_DOCUMENTS', COUNT(*) FROM KNOWLEDGE.OPERATIONAL_DOCUMENTS
UNION ALL SELECT 'AI.ANOMALY_SIGNALS', COUNT(*) FROM AI.ANOMALY_SIGNALS
UNION ALL SELECT 'AI.RECOMMENDATIONS', COUNT(*) FROM AI.RECOMMENDATIONS
UNION ALL SELECT 'GOVERNANCE.APPROVAL_DECISIONS', COUNT(*) FROM GOVERNANCE.APPROVAL_DECISIONS
UNION ALL SELECT 'GOVERNANCE.EXECUTED_ACTIONS', COUNT(*) FROM GOVERNANCE.EXECUTED_ACTIONS
UNION ALL SELECT 'GOVERNANCE.AUDIT_LOG', COUNT(*) FROM GOVERNANCE.AUDIT_LOG
ORDER BY table_name;
